trigger:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: self
variables:
- name: dockerRegistryServiceConnection
  value: '014fc65f-6b0d-4e1e-99fc-7d92b6048ca1'
- name: imageRepository
  value: 'pruebatecnica'
- name: containerRegistry
  value: 'awonose.azurecr.io'
- name: dockerfilePath
  value: '$(System.DefaultWorkingDirectory)/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: imagePullSecret
  value: 'awonose5e81-auth'
- name: vmImageName
  value: 'ubuntu-latest'
- name: k8sNamespaceForPR
  value: 'review-app-$(System.PullRequest.PullRequestId)'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: ecdc45f6-832d-4ad9-b52b-ee49e94659be@0
      inputs:
        targetPath: manifests
        artifactName: manifests
- stage: Analysis
  displayName: 'SonarQube Analysis'
  jobs:
  - job: SonarQubeJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python version for SonarQube analysis'
    - task: CmdLine@2
      displayName: 'Run SonarQube analysis and check Quality Gate'
      inputs:
        script: |
          # Run SonarQube analysis
          sonar-scanner -Dsonar.projectKey=my-project-key -Dsonar.sources=.

          # Check the quality gate status
          QUALITY_GATE_STATUS=$(sonar-scanner -Dsonar.projectKey=my-project-key -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.projectStatus=ERROR -Dsonar.qualitygate.timeout=300)

          if [[ "$QUALITY_GATE_STATUS" == *"ERROR"* ]]; then
              echo "SonarQube analysis failed (Quality Gate failed)"
              exit 1
          else
              echo "SonarQube analysis succeeded (Quality Gate passed)"
          fi
- stage: ParallelJobs
  displayName: 'Parallel Jobs'
  jobs:
  - job: Job1
    steps:
    - task: CmdLine@2
      displayName: 'Imprime Hola Mundo 10 veces en pantalla'
      inputs:
        script: |
          for i in {1..10}
          do
              echo "Hola Mundo $i"
          done
  - job: Job2
    steps:
    - task: CmdLine@2
      displayName: 'Crea 10 archivos con la fecha y los imprime en consola'
      inputs:
        script: |
          for i in {1..10}
          do
              echo "Creando archivo $i con fecha $(date)"
              echo "Creando archivo $i con fecha $(date)" > archivo_$i.txt
          done
- stage: Deploy
  displayName: Deploy stage
  dependsOn:
  - Build
  jobs:
  - deployment: Deploy
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment:
      name: 'PruebaTecnica.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
  - deployment: DeployPullRequest
    displayName: Deploy Pull request
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull/'))
    pool:
      vmImage: $(vmImageName)
    environment:
      name: 'PruebaTecnica.$(k8sNamespaceForPR)'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ReviewApp@0
            inputs:
              resourceName: default
          - task: Kubernetes@1
            displayName: 'Create a new namespace for the pull request'
            inputs:
              command: apply
              useConfigurationFile: true
              inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "$(k8sNamespaceForPR)" }}'
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              namespace: $(k8sNamespaceForPR)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          - task: KubernetesManifest@0
            displayName: Deploy to the new namespace in the Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sNamespaceForPR)
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
          - task: Kubernetes@1
            name: get
            displayName: 'Get services in the new namespace'
            continueOnError: true
            inputs:
              command: get
              namespace: $(k8sNamespaceForPR)
              arguments: svc
              outputFormat: jsonpath='http://{.items[0].status.loadBalancer.ingress[0].ip}:{.items[0].spec.ports[0].port}'
          - task: CmdLine@2
            inputs:
              script: |-
                url="$(get.KubectlOutput)"
                message="Your review app has been deployed"
                if [ ! -z "$url" -a "$url" != "http://:" ]
                then
                  message="${message} and is available at $url.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app."
                fi
                echo "##vso[task.setvariable variable=GITHUB_COMMENT]$message"

